// lib/email.js
//
// Application-triggered email using Resend.
//
// This file handles:
// - Signup confirmation email
// - Welcome email
// - Promotional email
//
// Supabase Auth generates the secure signup confirmation URL.
// This file only delivers that URL through Resend.
//
// IMPORTANT:
// Do not generate or modify Supabase confirmation tokens here.

const RESEND_ENDPOINT = 'https://api.resend.com/emails'

// ---------------------------------------------------------------------
// Resend sender
// ---------------------------------------------------------------------

async function sendViaResend(env, { to, subject, html }) {
  if (!env.RESEND_API_KEY) {
  throw new Error(
    'RESEND_API_KEY is not configured'
  )
}

if (!env.EMAIL_FROM_ADDRESS) {
  throw new Error(
    'EMAIL_FROM_ADDRESS is not configured'
  )
}


  const res = await fetch(RESEND_ENDPOINT, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${env.RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: env.EMAIL_FROM_ADDRESS,
      to,
      subject,
      html,
    }),
  })

  if (!res.ok) {
  const detail = await res.text().catch(() => '')

  console.error('[email] Resend API error', {
    status: res.status,
    detail,
  })

  throw new Error(
    `Resend send failed (${res.status}): ${detail}`
  )
}

// ---------------------------------------------------------------------
// HTML escaping
// ---------------------------------------------------------------------

function escapeHtml(str) {
  return String(str).replace(
    /[&<>"']/g,
    (ch) =>
      ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#39;',
      })[ch]
  )
}

// ---------------------------------------------------------------------
// Signup confirmation email
//
// confirmationUrl MUST be the action_link generated by Supabase:
//
// supabase.auth.admin.generateLink({
//   type: 'signup',
//   ...
// })
//
// We do not create or modify the URL ourselves.
// ---------------------------------------------------------------------

export async function sendConfirmationEmail(
  env,
  { to, displayName, confirmationUrl }
) {
  if (!confirmationUrl) {
    throw new Error(
      'Confirmation email cannot be sent without confirmationUrl'
    )
  }

  const name = escapeHtml(displayName || 'there')
  const url = escapeHtml(confirmationUrl)

  return sendViaResend(env, {
    to,
    subject: 'Confirm your BharatSpace email',
    html: `
      <div
        style="
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #222;
          max-width: 600px;
          margin: 0 auto;
          padding: 24px;
        "
      >
        <h2>Welcome to BharatSpace, ${name}!</h2>

        <p>
          Thanks for creating your BharatSpace account.
        </p>

        <p>
          Please confirm your email address to activate your account.
        </p>

        <p style="margin: 28px 0;">
          <a
            href="${url}"
            style="
              display: inline-block;
              padding: 12px 22px;
              background: #f59e0b;
              color: #111827;
              text-decoration: none;
              border-radius: 8px;
              font-weight: 600;
            "
          >
            Confirm my email
          </a>
        </p>

        <p>
          If the button doesn't work, copy and paste this link
          into your browser:
        </p>

        <p style="word-break: break-all;">
          ${url}
        </p>

        <p>
          If you did not create a BharatSpace account,
          you can safely ignore this email.
        </p>

        <p>
          — The BharatSpace team
        </p>
      </div>
    `.trim(),
  })
}

// ---------------------------------------------------------------------
// Welcome email
//
// This remains available for other parts of your application.
//
// IMPORTANT:
// If you send both confirmation + welcome during signup,
// the user will receive TWO emails.
// ---------------------------------------------------------------------

export async function sendWelcomeEmail(env, {
  to,
  displayName,
}) {
  const name = escapeHtml(displayName || 'there')

  return sendViaResend(env, {
    to,
    subject: 'Welcome to BharatSpace',
    html: `
      <div
        style="
          font-family: Arial, sans-serif;
          line-height: 1.6;
          color: #222;
          max-width: 600px;
          margin: 0 auto;
          padding: 24px;
        "
      >
        <h2>Welcome to BharatSpace, ${name}!</h2>

        <p>
          We're glad to have you here.
        </p>

        <p>
          Your BharatSpace account has been created successfully.
        </p>

        <p>
          Please confirm your email address before signing in.
        </p>

        <p>
          — The BharatSpace team
        </p>
      </div>
    `.trim(),
  })
}

// ---------------------------------------------------------------------
// Promotional email batch
// ---------------------------------------------------------------------

export async function sendPromotionalEmailBatch(
  env,
  { recipients, subject, html },
  { batchSize = 20 } = {}
) {
  const results = {
    sent: 0,
    failed: 0,
    skipped: false,
  }

  if (
    !env.RESEND_API_KEY ||
    !env.EMAIL_FROM_ADDRESS
  ) {
    results.skipped = true
    return results
  }

  for (
    let i = 0;
    i < recipients.length;
    i += batchSize
  ) {
    const batch = recipients.slice(
      i,
      i + batchSize
    )

    const outcomes = await Promise.allSettled(
      batch.map((to) =>
        sendViaResend(env, {
          to,
          subject,
          html,
        })
      )
    )

    for (const outcome of outcomes) {
      if (outcome.status === 'fulfilled') {
        results.sent += 1
      } else {
        results.failed += 1

        console.error(
          '[email] promotional send failed for one recipient',
          outcome.reason
        )
      }
    }
  }

  return results
}
